[package]
name = "lean-stacks-project"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "33be7dcc99c089554d45dd3d8a183ac4b832f209"}
lean-category-theory = {git = "https://github.com/semorrison/lean-category-theory", rev = "5304663e2845fac56b90cbc6c7735ff04a70b794"}
